theme = "penumbra+dark"

[editor]
idle-timeout = 200
line-number = "relative"

[keys.normal]
"X" = "extend_line_up"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "╎"