theme = "tokyonight+dark"

[editor]
true-color = true
idle-timeout = 280
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "╎"

[keys.normal]
X = "extend_line_up"
ret = ["move_line_down", "goto_line_start"]

[keys.normal.g]
q = ":reflow"
G = "goto_file_end"

[keys.normal.space]
q = ":quit"
# w = ":write"
